---
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - config/**/*
    - bin/**/*
    - vendor/**/*
  Include:
    - Gemfile
    - "**/Rakefile"
    - "**/config.ru"
    - "**/*.rake"

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - spec/requests/**/*

RSpec/DescribedClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectActual:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/AlignHash:
  EnforcedLastArgumentHashStyle: ignore_implicit

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/PredicateName:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false
