default: &default
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  sms_provider_id: <%= ENV.fetch("SMS_PROVIDER_ID") %>
  sms_provider_secret: <%= ENV.fetch("SMS_PROVIDER_SECRET") %>
development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
