User.create!(name: 'The Book', email: "darryn.campbell@gmail.com", mobile: "+16179218408", admin: true)

Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'BUF', region: 'Buffalo', name: 'Bills')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'MIA', region: 'Miami', name: 'Dolphins')
Competitor.create!(sport: :nfl, nicknames: ['Pats'], abbreviation: 'NE', region: 'New England', name: 'Patriots')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'NYJ', region: 'New York', name: 'Jets')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'BAL', region: 'Baltimore', name: 'Ravens')
Competitor.create!(sport: :nfl, nicknames: ['Cincy'], abbreviation: 'CIN', region: 'Cincinnati', name: 'Bengals')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'CLE', region: 'Cleveland', name: 'Browns')
Competitor.create!(sport: :nfl, nicknames: ['Pitts'], abbreviation: 'PIT', region: 'Pittsburgh', name: 'Steelers')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'HOU', region: 'Houston', name: 'Texans')
Competitor.create!(sport: :nfl, nicknames: ['Indy'], abbreviation: 'IND', region: 'Indianapolis', name: 'Colts')
Competitor.create!(sport: :nfl, nicknames: ['Jags', 'Jacks'], abbreviation: 'JAX', region: 'Jacksonville', name: 'Jaguars')
Competitor.create!(sport: :nfl, nicknames: ['Tenn'], abbreviation: 'TEN', region: 'Tennessee', name: 'Titans')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'DEN', region: 'Denver', name: 'Broncos')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'KC', region: 'Kansas City', name: 'Chiefs')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'LV', region: 'Las Vegas', name: 'Raiders')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'LAC', region: 'Los Angeles', name: 'Chargers')
Competitor.create!(sport: :nfl, nicknames: ['Boys'], abbreviation: 'DAL', region: 'Dallas', name: 'Cowboys')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'NYG', region: 'New York', name: 'Giants')
Competitor.create!(sport: :nfl, nicknames: ['Phily', 'Philly'], abbreviation: 'PHI', region: 'Philadelphia', name: 'Eagles')
Competitor.create!(sport: :nfl, nicknames: ['Redskins', 'Skins', 'Football Team'], abbreviation: 'WAS', region: 'Washington', name: 'Commanders')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'CHI', region: 'Chicago', name: 'Bears')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'DET', region: 'Detroit', name: 'Lions')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'GB', region: 'Green Bay', name: 'Packers')
Competitor.create!(sport: :nfl, nicknames: ['Minny'], abbreviation: 'MIN', region: 'Minnesota', name: 'Vikings')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'ATL', region: 'Atlanta', name: 'Falcons')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'CAR', region: 'Carolina', name: 'Panthers')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'NO', region: 'New Orleans', name: 'Saints')
Competitor.create!(sport: :nfl, nicknames: ['Bucs', 'Buccs', 'Tampa', 'Tam'], abbreviation: 'TB', region: 'Tampa Bay', name: 'Buccaneers')
Competitor.create!(sport: :nfl, nicknames: ['Zona', 'Cards'], abbreviation: 'ARI', region: 'Arizona', name: 'Cardinals')
Competitor.create!(sport: :nfl, nicknames: [], abbreviation: 'LAR', region: 'Los Angeles', name: 'Rams')
Competitor.create!(sport: :nfl, nicknames: ['Forty Niners', 'Forty-Niners', '9ers', 'Niners'], abbreviation: 'SF', region: 'San Francisco', name: '49ers')
Competitor.create!(sport: :nfl, nicknames: ['Hawks'], abbreviation: 'SEA', region: 'Seattle', name: 'Seahawks')
